apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZGZvMUFWMi82OTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1qRXdNVFV6TWpkYUZ3MHpOakExTVRnd01UVTRNamRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURQTm9UT21Cbk1FbnhRYXMrYkY2aEphakRlU01JdWNVaCtONkpFR3ZJYnJWSWlDMFhJVlZFQVVWbmsKTlBJY2p5dnJBdllTNzlITjQ0YjFicE5yeHRXckFSem1GcWZ5b20xa1AwbS95Zkg0eGxDNUw4eWE5S0UwTjFoNAo2QUl5SjJyZFZYTEt3S292MnhwYzdqSEFnZ2ZiY0MwalIvQzhPWFhMR2R5Sm16ZUJPYktRWjZzTUtKeXFrSlRVCmZBT2dnUnUvbHNlMC9KVStZN055U3FUT2tWMjc4cHQxelF6M3JiY3B4dkp0Nzc5dWZJcVVwK1pZS2tYTU5tZ1UKTkVQVXpSeWMva2cvTFYvZjlpS3d0aXhYck5IUHg3N1o2VlZMZEVGakRmLzFmM2UvMmFDVy91QTFTcnZBMjc1dwp2SHJaT1Q0TUxXdkpDSzA2bHo0U0ZGMy9mdlpMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUMVAycnZmb2JrMzEzeFNqR2NYNVo2ZEJtVm9EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ20vS0dVSmk3ZwpHdll5bWU3M1VTYmd2SXBuMnp4aDdoRElmVDFzWmZ5bm9IUHFFTXlPZktGTnNkemNpZ2RiRVYzRGpKK1h0S3h0CmE2S3lzS1V2V01hYk9SeVlFb0lVTmx5aFIrN2RxYUxLUCs0OWp3RmhwYmpVSk5OLzZkUzhCQVBRWGJvTmJmaWcKN1ppc3pPSS9IU2dwYTJpdFh3S1Q1UkF1dndTTDV5Rno5N2lCb3A4UG5QU0wrVk05U1BSOWhnZlR1TEVzVmVEUwppNDczK0txRytuSm04bFBtTG9mQktkaVRzUlhpVWpNL2wyclNwNjhlQ05XemUyclZrQlZiQXdtVmVzbmhDdjQwCjhWT0dZbkM4Qi84ZzBNMkZCUktwOHhIc0R6a2Z1QWVtODIxejlmOWI3QmhzYmxNQncrclc0VDFkalVpR3d6a0cKQkhzYkgrRFFhRE1aCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://688427BCF478B70704248A32CFCF7F16.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:337748711987:cluster/demo-eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:337748711987:cluster/demo-eks-cluster
    user: arn:aws:eks:us-east-1:337748711987:cluster/demo-eks-cluster
  name: arn:aws:eks:us-east-1:337748711987:cluster/demo-eks-cluster
current-context: arn:aws:eks:us-east-1:337748711987:cluster/demo-eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:337748711987:cluster/demo-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - demo-eks-cluster
      - --output
      - json
      command: aws
